### ISSUE TITLE
Exactly what I want but can't get anything to work

### ISSUE THREAD

**Issue by jacksoncooper12** [fznhq/userscript-collection#1]
The description of this sounds absolutely perfect. It is exactly what I am looking for. Unfortunately, I cannot get it to work, and I really don't know what to check for. I've tried running it as-is. I've tried flipping various flags in the code. I've tried pressing "v" on a YouTube video. Not sure what else to do or say, but I'm glad to provide any necessary info. As an example, [this userscript ](https://greasyfork.org/scripts/454092)works as expected as soon as it is installed, but it's nowhere near as nice as this one seems to be.

**Comment by fznhq** [comment]
May I ask you a bit? What userscript extension are you using right now? And is there any error in the console log on the browser? thanks

**Comment by jacksoncooper12** [comment]
Absolutely! it is this extension:
https://greasyfork.org/en/scripts/480701-youtube-fullpage-theater

This is the only thing about the extension in the console after injecting:
[Warning] Youtube Fullpage Theater.user.js @inject-into value set to 'content' due to @grant values: GM.getValue,GM.setValue - https://github.com/quoid/userscripts/issues/265#issuecomment-1213462394 (userscripts.js, line 1)

**Comment by fznhq** [comment]
Sorry, what I mean is what browser extension you use right now to run userscript

**Comment by jacksoncooper12** [comment]
My apologies; I am using the Userscripts extension for safari on MacOS.

**Comment by fznhq** [comment]
Can you try again now? Install it from [here](https://github.com/fznhq/userscript-collection/raw/main/Youtube_Fullpage_Theater.user.js) for now, and after it's confirmed working, I will update greasyfork

**Comment by jacksoncooper12** [comment]
Still no luck unfortunately

**Comment by fznhq** [comment]
Is there still any error? Can you tell me

**Comment by fznhq** [comment]
While we're here, can you help me `console.log(window)` on my script? And tell me what the output is. thanks

**Comment by fznhq** [comment]
Can you try again? [install](https://github.com/fznhq/userscript-collection/raw/main/Youtube_Fullpage_Theater.user.js)

**Comment by fznhq** [comment]
@jacksoncooper12 Try again, it should be working right now. You can install it from github or greasyfork
